### PR TITLE
Added needed binaries for Raspberry Pi 3 ARMv7 into tools

### PR DESCRIPTION
**Pull request by tekk**
Hi Roger, I've read thread on the forum [about compiling arduino under Raspberry Pi](http://www.stm32duino.com/viewtopic.php?t=972) and I tried it myself. And since I've recompiled almost everything from scratch, I thought it was a good idea to make a pull request with the updated binaries. These won't probably work on RPi 1, 2... It's only for RPi 3.
Basically what I did was to copy the `tools\linux` directory into `tools\rpi` and replaced all necessary binaries for the ARMv7 platform.
One exception, as mentioned in `/tools/rpi/stlink/README.md`, `st-term` utility is still missing.
But it's a WIP.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
@tekk 

Thanks for this submission.

I think its really good, but I have a concern about how much bigger it makes the repo.

Its it necessary to include the source to the tools, or is the code identical to the linux source.

Also I noticed that you seem to have committed various log files specific to when you ran lsusb and various other diagnostics.  I'm pretty sure they would not be needed

**Comment by tekk** [comment]
@rogerclarkmelbourne 
Sorry for late response.
In this commit I've included sources I've used.
The repo would be 2,4MB bigger, I've just `du`'d the *tools/rpi* directory.
Soruces are cleaned, (`make clean`) to get rid of unnecessary object files etc.
I'm not aware about commiting any log files, could you please point me out?
Thanks!

**Comment by tekk** [comment]
@rogerclarkmelbourne 
Oh, now looking at the sources I know what log files you mean, `tools/rpi/src/dfu-util/device-logs/*.log`... but they're not mine, they come from [here](https://github.com/Stefan-Schmidt/dfu-util/tree/master/device-logs) on the [dfu-util repo](https://github.com/Stefan-Schmidt/dfu-util) that I've used. I don't know where to get the "proper" sources. Maybe you could point me out on this too.
Many thanks!

**Comment by rogerclarkmelbourne** [comment]
@tekk 

I think you took out the upload log files when you did your last commit.

But I've not had time to download and test your latest version yet.

**Comment by rogerclarkmelbourne** [comment]
I think someone else is trying this, so I'll wait for them to report back about their experiences, via the forum

**Comment by rogerclarkmelbourne** [comment]
There still appears to be log files in the PR

Note. I've created a forum thread to discuss this

http://www.stm32duino.com/viewtopic.php?f=53&t=2278

**Comment by rogerclarkmelbourne** [comment]
As this would make the repo a lot bigger for everyone, I've put it into a separate branch

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/LimitedRPiSupport

**Comment by tekk** [comment]
Thanks Roger.

**Comment by rsonnicksen** [comment]
@tekk 
I'm trying to migrate a blue pill development effort from Win10 using Arduino IDE to RPi4.
I confess to be quite illiterate in Linux.  Having issues just getting started trying to load Blink into Blue Pill, getting errors on stm32flash which is probably due to this exe compiled for x86, not armv7.   I'm using FTDI tool to flash blue pill.  Any guidance on steps to get this working?  Thx

**Comment by tekk** [comment]
@rsonnicksen It's a long time I've been doing this. I don't have any specific additional information regarding this topic. Have you tried the repo that Roger created? Things may have changed for the latest Raspbian.

**Pull request closed without merging**
