### PR TITLE
uploading with openocd for STM32F1 boards

### PR DESCRIPTION
**Pull request by on1arf**
Hi Roger,

(I'm sorry, I am still pretty new to github).

As requested, the pull request.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Did you intentioinally remove the stuff about the HSI on the Nucleo board ?

You also seem to have changed something to do with build archive path in platform.txt which I woudlnt have expected to be part of this change.

https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/171/files


This may have been caused because you cloned the repo several months ago, but I thought you had cloned it recently?

Thanks

As it standards I can't accept the PR as it would break the nucleo HSI and some other things

**Comment by on1arf** [comment]
Roger,


Oeps ...  the changes about the HSI where surely not planned. (nor the 
typo :-( )

The file I send you where based on the changes I did a couple of months 
ago, so it is very well possible that -indeed- there is a mix-up of 
versions here. My applologies about that.


The difficult with openocd is -I think- the configuration-file as it 
contains a reference to the jtag-interface that is used. In my case, it 
is "+source [find interface/olimex-arm-usb-tiny-h.cfg] " for the olimex 
jtag debugger.
People using other jtag debuggers will need to fill in something else.

I have no idea how you would incorperate this in the arduino IDE in a 
user-friendly way.


BTW. As you mention the nucleo-board, how do they represent theirselfs? 
As a stlink debugger or a mbed CMSIS-DAP interface?

I used openocd to flash and debug a mbed board (lpc1549 expresso board) 
using its mbed / CMSIS-DAP interface and it does work so openocd might 
be an option in these cases too.



Cheerio! Kr. Bonne.

**Comment by RickKimball** [comment]
Nucleo boards are STLink-V2-1 ... interface/stlink-v2-1.cfg.

**Comment by rogerclarkmelbourne** [comment]
Umm

I guess I could make these changes manually myself

Basically its just a few lines in platform.txt and boards.txt plus 2 new files for linux

Ideally we'd also have OSX and Windows support, and also if this is applicable to all boards, the new upload methods should be available on all boards, not just the one you have.

**Comment by rogerclarkmelbourne** [comment]
I just looked at your PR again, but there are a number of things wrong with the code

1. You changed settings on an existing board (Nucleo)
2. Your upload script uses a hard coded path that only works on your machine
3. It looks like you referenced openocd files which were now included in the PR

I would love to add openOCD support, but this PR would only work for you and one one else

Please.
1. Pull the latest version of the repo, and add a new upload method to the nucleo board, but dont change any other settings
2. Remove the hard coded paths
3. Include all dependant files as part of the PR, including openocd binaries and config files
4. Preferably also do this for Windows and OSX users as well, as 90% of the community uses Windows.

**Comment by rogerclarkmelbourne** [comment]
@on1arf 

Do you have any plans to make your changes generic so they will work on all machines (e.g. fix the hard coded paths etc)

If not, I will close this issue, as I don't like to keep dormant issues open indefinitely.

**Comment by on1arf** [comment]
Roger,


I'm sorry for the delay. I did see your message but it got burried under 
a ton of other stuff at that time :-(




On 17-06-16 00:13, Roger Clark wrote:
>
> @on1arf <https://github.com/on1arf>
>
> Do you have any plans to make your changes generic so they will work 
> on all machines (e.g. fix the hard coded paths etc)
>

I think there has been a big misunderstanding about this.

The reason I wrote about openocd in the forum was "this is how I do it, 
I don't know if it might be usefull for you and I have no idea how to 
implement this in a GUI". It was not intended to be a "ready to use" 
patch (to be posted on github), just a starter for discussion.


As mentioned before, the issue is not the hard-coded path or even having 
openocd on the box, the main problem I see is that the openocd 
configuration file has two parts: one for the target, and one for the 
jtag/swd interface.
If you concider the IDE a "ready to use"  interface that requires no 
manual fidling in files, I am not sure how you would create the latter 
part. Create a list of all these different jtag interfaces and add them 
to the arduino ide in some drop-down list somewhere?
Nah. In fact, at tthat point, you are become more or less 
release-manager for openocd-on-stm32duino.

You can ask yourself "is it all worth it", especially as the really 
interesting use of jtag and openocd is real-time debugging, ... but the 
arduino IDE does not support that anyway. The added value of using 
openocd and jtag as a just a programmer isn't all that great. I just 
concidered it to be a "nice to have as it can be done" but not more.



An additional note:
As you say a that then openocd (in source) needs to be added to 
stm32duino, I wonder if it would not be possible to use any version of 
openocd already on the system. (IDEs have the tendency of growing into 
these giant blobs of code, usually duplicating tools you already have on 
your system anyway).

Is there no way to do this the other way around: run a script at startup 
that detects if openocd (and what version) is on the system and create 
the configuration for the arduino IDE menus dynamically on that.

If you use the version of openocd that is already on the box, it removes 
the requirement to effectively become release-manager for 
openocd-under-stm32duino; which very probably is a lot of hassle for 
relative little gain.






> If not, I will close this issue, as I don't like to keep dormant 
> issues open indefinitely.
>
As explained, this code was only intended for a discussion; and should 
never have been on github  anyway; so feel free to close the ticket.


(Anycase, my arduino IDE enviroment on my box is currently completely 
broken, so I cannot test this anyway).




Cheerio! Kr. Bonne.

**Comment by rogerclarkmelbourne** [comment]
Hi Bonne,

OK.
It sounds far more complex than I had thought.

I will need to find somewhere to document what you did, as a github issue is probably not the best place.

Perhaps I should put this in the wiki pages here on github, or I now have a wiki on the stm32duino.com forum domain  wikistm32duino.com
(but at the moment that wiki is not structured with a good place to put your information)

I will leave the issue open to remind me I have to document the openocd procedure somewhere

Thanks

Roger

**Comment by rogerclarkmelbourne** [comment]
Although it would be good to add OpenOCD support, any PR would need to have support for all platforms and work on machines with different paths and foldernames to your specific machine.

So I will need to close this PR as not currently viable

Please feel free to resubmit if you fix the paths and other issues and add support for the other OS's

**Pull request closed without merging**
