### PR TITLE
Added support to HID Bootloader 2.0

### PR DESCRIPTION
**Pull request by Serasidis**
HID Bootloader 2.0 supports Bluepill and generic_f407v boards
The hid-flash tool is at the moment available only on Windows

Please update your HID Bootloader firmware to V2.0
(https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F1/bootloader_only_binaries)
(https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F4/bootloader_only_binaries)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Cool.

I'll take a look....

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I downloaded your latest version of the bootloader and installed onto my modified BP (with pull up resistor fixed), and it works very well.

Seems to be faster than DFU and also is smaller !

Excellent work.

After a few more people test it, this upload option could be added to the other boards e.g. the R,V and Z series'

Thanks again.

**Comment by Serasidis** [comment]
The HID Bootloader v2.0 source code for STM32F407 has been released
https://github.com/Serasidis/STM32_HID_Bootloader/tree/master/bootloader_F4

**Comment by Serasidis** [comment]
@rogerclarkmelbourne 
I added the **hid-flash** tool for Mac and Linux in the patch file 
**Arduino_STM32_patch_180809_02.zip**

**Pull request merged**
