### PR TITLE
Update timer.h

### PR DESCRIPTION
**Pull request by stevstrong**
fix compile error for #491

### CODE REVIEW

**Comment by stevstrong** [comment]
I have tested now and it seems to work.

**Comment by rogerclarkmelbourne** [comment]
This looks like its superseded

**Comment by edogaldo** [comment]
Sorry @rogerclarkmelbourne and @stevstrong, I'm missing why this should be superseded, clould you please explain?

Thanks in advance, E.

**Comment by stevstrong** [comment]
Roger, it seems that the fix is still not merged in the core.
Edogaldo has merged its own version in his own repo, which version is similar to mine.
But none of them was merged here.

**Comment by rogerclarkmelbourne** [comment]
OK

If this PR is still valid I will merge it

**Comment by edogaldo** [comment]
Well, this PR is more than 1 month old so day +/day -... :)
Anyway I think this is a required fix..

**Pull request merged**
