### PR TITLE
corrected typo - ADC_CR2_TSVREFE

### PR DESCRIPTION
**Pull request by stevstrong**
seems to be not critical

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
We'd also need to change the example that uses it


https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/2e9b4f3955aa648bcc78301529b74ea652a9f4d8/examples/MrBrunetteExamples/InternalTempSensor/InternalTempSensor.ino

line 22

Preferably we also update the GD32 and STM32F4 as well, but I can do those two

**Comment by stevstrong** [comment]
OK, thanks.

**Comment by rogerclarkmelbourne** [comment]
Steve,

I'm made a new branch called development and have effectively pulled your PR's into that branch

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/development

I'll post to the forum and perhaps some of the others will have time to pull and switch to that branch and test.

I did a quick test with a board that has an SPI LCD attached and it still works fine, however getting by SD test rig (breadboard) into a state where I can run it will take longer as its been in a cupboard for a while and also I took out the SD card to use for something else

**Comment by stevstrong** [comment]
Hi Roger,
```
I'm made a new branch called development and have effectively pulled your PR's into that branch
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/development
I'll post to the forum and perhaps some of the others will have time to pull and switch to that branch and test.
```
It's a good idea, hopefully there will be some volunteers to test this branch.

**Comment by rogerclarkmelbourne** [comment]
Hi Steve,

I think the problem is that hardly anyone uses Git to update their local copy :-(

And even less people have time to update and switch to the development branch.

So the only way I get extensive testing is to put stuff on the Master branch and wait weeks and weeks for people to update.
Or I just get issues when a new users downloads for the first time, which is not an ideal situation.

Anyway, I think this issue is basically resolved, so I'm going to close this PR so I can keep track of how many PR's still need to be actioned

**Pull request closed without merging**
