### PR TITLE
Spi callbacks

### PR DESCRIPTION
**Pull request by victorpv**
This has the addition of:
dmaSendSet
dmaSendRepeat
dmaTransferSet
dmaTransferRepeat
onTransmit
onReceive
EventCallback

I have added a few variables to the class to hold the "this" pointer for each port, so they should work fine with all 3 ports (I have tested SPI1 and SPI2 simultaneously, with different callback function for each).
It should also work with setModule, since the "this" pointer is in the settings class.

Changed TABs to spaces, previously was a mix of both, and I believe the preference is for spaces. If that's not the case I will resubmit with Tabs.

Finally, the only change to any other function is in dmaSendAsync, where I changed the variable used to hold whether there is a DMA transfer going on, so if dmaSend is used with callbacks (non-blocking) and you try to send with sendAsync, sendAsync will wait for the previous dma to be finished.
Thinking on it we should probably add the same check to the other functions.

### CODE REVIEW

**Comment by victorpv** [comment]
Furthermore, we could slightly modify the dmaSendAsync function to set the DMA ISR to EventCallback too.
That way when the DMA is over EventCallback will change the state variable to Ready (and call a user callback if one is set), and dmaSendAsync doesn't need to wait checking when the transfer is over, that will remove overhead in that function.

**Comment by rogerclarkmelbourne** [comment]
I've tested these changes with the graphics test sketch and it seems to still work fine

So I will merge the changes

**Comment by stevstrong** [comment]
Sorry to resurrect this but I am trying to port this code to F4 and have some issues when using dmaSendAsync() and dmaSend() in the same application, without specifying any callback for transfer/send.
I just wonder whether we could easy the application part if dmaSendAsync() could have an input parameter a variable which would be set when the transfer/send is done. This way the application could just poll that variable and do what needed in that case.
Otherwise the application should have its own function which sets that variable when the send/transfer is finished. More than that I cannot imagine that is meaningful to do in the attached event as callback function.
Or do you have some other concerns regarding this, Victor?

**Comment by victorpv** [comment]
I added a volatile in the code,  _state, that we can leverage for that.
I see multiple easy solutions:
1.- Add a new function to return whether the port is active or not. I need to check if the DMA ISR is always set, or only when there is a callback set. If the later, we can change it to the former. So the SPI DMA ISR can change that _state variable if is not doing so already.
2.- Add a new parameter to dmaSendAsync. That poses a risk of breaking existing code, so I kind of lean towards adding a new function that returns the state (states can be idle, ready-after begin() is called, TX when doing a TX, and RX when doing an RX). the function could also just return a bool, with true for TX or RX states, and false for anything else.
3.- Implement a callback function that controls a variable within the user sketch.

Roger uses the dmaSendAsync in a led driver library, so if we make any change to it, we need to test with that. There may be other people using the library or other code using the same function. As long as we can keep the code compatible with the existing calls, I don't see a reason to not make changes.

**Comment by stevstrong** [comment]
OK, 1 or 3 should be doable.
My problem during evaluating the live OV7670 project was that I had to call tft.setAddressWindow() without knowing the state of the async DMA called before, so it was sometimes conflicting with that.
Accordingly, an additional function which would return the state of the DMA (finished or not) would be really helpful. This would involve the existence of the SPI driver internal callback which sets the internal _state, right?

**Comment by victorpv** [comment]
Right. There is an internal callback within the SPI driver, but I don't remember if it's enabled or only when the user code sets a callback, I'll check that up later today and make the necessary changes.

**Comment by stevstrong** [comment]
OK, thaks.
In the same context, I think there is a potential problem with using dmaSendAsync() and dmaSend().
Even having defined a user callback, the dmaSendSet() will be executed regardless of internal _state, which I think is not wanted.
In my test version I made a separate function `dmaSendWaitCompletion()` which waits the internal _state to get ready, and I call this function at the beginning of each DMA send function, even for dmaSendSet(). This involves a small overhead, but I think this eliminates any conflicting situation, so it maybe makes sense.  What do you think?

**Comment by victorpv** [comment]
I think if we just checked the _state value instead should reduce the overhead from the calls, and still not take much more space.
But either way, I agree it should be guarded.

**Pull request merged**
