### PR TITLE
Fix formatting and typos in README.md

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
I cant see what you have changed

There seem to be changes which git noticed, which are not visible to the human eye

Perhaps different types of newlines

Why did you think there was a problem with the readme newlines ?

**Comment by per1234** [comment]
I made no changes to the newline type.

I guess you're talking about the trailing whitespace I removed?

**Comment by victorpv** [comment]
I see those, removed a bunch of trailing spaces. Seems fine to me.

**Comment by rogerclarkmelbourne** [comment]
OK

I'll merge it

**Pull request merged**
