### PR TITLE
F1: added function dma_get_count

### PR DESCRIPTION
**Pull request by stevstrong**
Utility function to check the number of transfer yet to be done by DMA.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Looks very low risk.

I think I can merge.

When is it used ?

**Comment by stevstrong** [comment]
It is useful to check if the DMA has finished the transfer, and if not it gives how many transfers are yet to be done.

**Comment by rogerclarkmelbourne** [comment]
ok.


thanks

**Comment by VictorLamoine** [comment]
@rogerclarkmelbourne for reference of an example use case: http://www.stm32duino.com/viewtopic.php?p=46799#p46799

Thanks @stevstrong

**Pull request merged**
