### PR TITLE
Upload fixes

### PR DESCRIPTION
**Pull request by kolyshkin**
I had a problem making maple_upload to work and ended up with a few fixes that might be useful to others. Please see the individual commit messages for detailed description.

### CODE REVIEW

**Comment by stevstrong** [comment]
Does this need further testing? If yes, can someone test it?
I have no Linux machine.

**Comment by stevstrong** [comment]
Anyone can test this on linux?

**Comment by AbdUslu91** [comment]
I tested under ubuntu 16.04. Working very well. I think this pr is necessary for fix some bugs.

**Comment by stevstrong** [comment]
OK, I will merge this.

**Pull request merged**
