### PR TITLE
CoOS 1.12 and 1.1.6 (latest), and FreeRTOS 8.2.1

### PR DESCRIPTION
**Pull request by victorpv**
Ported FreeRTOS 8.2.1 by finding the changes in the 7.0.1 version and
carrying them over. Then found an almost working port of CoOS 1.12 (a few years old), and
corrected it to work, and then carried the changes to 1.1.6 (latest). Tested all
of them with USBSerial, GPIO, SPI, and SPI DMA (with ISR and all).
Similar examples ported to all of them.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Victor.

Thanks.

I'll action the pull request, without testing it myself, as these are new libs so won't harm the core ;-)

Thanks again

roger

**Comment by victorpv** [comment]
Wait a minute, I noticed I left some files out of that commit, adding the rest.

**Comment by victorpv** [comment]
I'll send another pull request in a minute for the rest of the files as I see you accepted this one already.
BTW I ended up deleting my fork and forking again because trying to re-sync it was just causing more issues.

**Comment by rogerclarkmelbourne** [comment]
OK No worries

**Pull request merged**
