### PR TITLE
Necromancing libmaple I2C slave implementation [Experimental/Don't merge yet]

### PR DESCRIPTION
**Pull request by lacklustrlabs**
I've noticed that there once were an I2C slave implementation in libmaple.
They merged this code in 2013 and [removed it 2014](https://github.com/lacklustrlabs/libmaple/tree/I2C_slave_still_present), but I can't find why.

I've brought the i2c slave implementation back from the dead and merged it with the current code.
It seems to work with a limited example. It even works with master mode Wire.h ( Adafruit_SSD1306 )

I've tested `master_writer.ino` talking to `i2c_libmaple_slave.ino`. 

Obviously this needs extensive testing, and I can only test this on Maple Mini.

It seems like a large job to put slave mode into Wire.h, at least if done properly (individual buffers for both I2C channels, adhere to Stream API, etc etc) so that will have to be a separate PR.

All credit for this code should go to Barry Carter. barry.carter@gmail.com, headfuzz.co.uk who wrote this back in 2012.

#207 #324

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
It would be good to have I2C slave, but I think its going to take a while before enough testing can be done on this change, as it changes deep inside the core.

Also, one minor thing you can do... Change the examples that have the extension of .pde to .ino

**Comment by rogerclarkmelbourne** [comment]
BTW. Did you try to email barry.carter ? It wouldnt do any harm.

**Comment by lacklustrlabs** [comment]
Yes, I'm aware that these changes will take time to verify and test. Maybe we can add them to a special branch in the main repository, that way it will be easier to test.  - no need to download my fork, mess with symbolic links under Arduino/hardware etc, etc.

I took the examples from https://github.com/stm32duino/Arduino_Core_STM32, but I think I'll replace them with https://github.com/arduino/ArduinoCore-sam (Due). The Due code seems more up to date.
 
I did not try to contact Barry, yet. But I'll do that later today.


There were only one conflicting section in i2c.c. Here is the libmaple version:
```
    /*
     * EV6: Slave address sent
     */
    if (sr1 & I2C_SR1_ADDR) {
        /*
         * Special case event EV6_1 for master receiver.
         * Generate NACK and restart/stop condition after ADDR
         * is cleared.
         */
        if (read) {
            if (msg->length == 1) {
                i2c_disable_ack(dev);
                if (dev->msgs_left > 1) {
                    i2c_start_condition(dev);
                    I2C_CRUMB(RX_ADDR_START, 0, 0);
                } else {
                    i2c_stop_condition(dev);
                    I2C_CRUMB(RX_ADDR_STOP, 0, 0);
                }
            }
        } else {
            /*
             * Master transmitter: write first byte to fill shift
             * register.  We should get another TXE interrupt
             * immediately to fill DR again.
             */
            if (msg->length != 1) {
                i2c_write(dev, msg->data[msg->xferred++]);
            }
        }
        sr1 = sr2 = 0;
    }
```

And here is what I merged it into (I kept our version) : i2c.c line 532:
```
    /*
     * EV6: Slave address sent
     */
    if (sr1 & I2C_SR1_ADDR) {
        /*
         * Special case event EV6_1 for master receiver.
         * Generate NACK and restart/stop condition after ADDR
         * is cleared.
         */
        if (read) {
            if (msg->length == 1) {
                i2c_disable_ack(dev);
                if (dev->msgs_left > 1) {
                    i2c_start_condition(dev);
                    I2C_CRUMB(RX_ADDR_START, 0, 0);
                } else {
                    i2c_stop_condition(dev);
                    I2C_CRUMB(RX_ADDR_STOP, 0, 0);
                }
            }
        } else {
            /*
             * Master transmitter: write first byte to fill shift
             * register.  We should get another TXE interrupt
             * immediately to fill DR again.
             */
            if (msg->length > 1) {
                i2c_write(dev, msg->data[msg->xferred++]);
            } else if (msg->length == 0) { /* We're just sending an address */
                i2c_stop_condition(dev);
              /*
               * Turn off event interrupts to keep BTF from firing until
               * the end of the stop condition. Why on earth they didn't
               * have a start/stop condition request clear BTF is beyond
               * me.
               */
              i2c_disable_irq(dev, I2C_IRQ_EVENT);
              I2C_CRUMB(STOP_SENT, 0, 0);
              dev->state = I2C_STATE_XFER_DONE;
            } /* else we're just sending one byte */
        }
        sr1 = sr2 = 0;
    }
```

**Comment by rogerclarkmelbourne** [comment]
OK.

I could make a branch, but I doubt anyone else would bother to test it.

I find the only way to get anyone to test things is just to add them to the master branch, if they seem OK for me, and then wait for people to scream ;-)

I think this would be a good addition, but as you know there are loads of other changes pending, some of which are less invasive. 
Hence when I get time to process PR's, I normally try to get the less dangerous ones tested and hopefully merged first.

So this one will just take a bit longer.

If I get time, I'll try to check you did the Hardware I2C PR, as they may be worth asking, as they are going to be far more of an expert on I2C than I am

**Comment by lacklustrlabs** [comment]
@rogerclarkmelbourne Do you want me to add my changes to Wire, SoftWire and BaseWire to this PR?

I'm thinking about making our Wire implementation public-signature-identical to Due Wire.h. 
\- e.g inherit from Stream.h, check all method signatures, add receive buffers, etc etc

This will probably have an even greater impact on the rest of the repository.

**Comment by victorpv** [comment]
Do this require changes to the core files, or just the library files? If the later, then perhaps could be added as a second library in another folder to let people test .

**Comment by rogerclarkmelbourne** [comment]
It changes the core

STM32F1/cores/maple/libmaple/i2c.c 

etc

**Comment by stevstrong** [comment]
It would be more safe if one could somehow export the added slave functions into separate file(s) (i2c_slave.c, i2c_slave.h ?).

**Comment by rogerclarkmelbourne** [comment]
@stevstrong 

It looks like some changes to existing functions are essential, e.g. it seems to do something with an IRQ ("fix")

**Comment by stevstrong** [comment]
If you mean the `_i2c_irq_priority_fixup` this contains only [two lines](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/4021c32fdb809f16a61c073d04e1d8c2c487a767/STM32F1/cores/maple/libmaple/i2c_f1.c#L99) which are already included in the [`i2c_master_enable`](https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/4021c32fdb809f16a61c073d04e1d8c2c487a767/STM32F1/cores/maple/libmaple/i2c.c#L197) function.
I still think that it would be possible to separate the slave functions from the master ones.

**Comment by lacklustrlabs** [comment]
Yes, I think it would be possible to include all of this in a Wire_Slave library, but then that library would have to include a custom libmaple i2c_slave class. Certainly doable, at least for testing purposes

**Comment by lacklustrlabs** [comment]
Quick and dirty library-only version of all this: https://github.com/lacklustrlabs/Arduino_STM32/tree/WireSlave/STM32F1/libraries/WireSlave  (note that this is another branch)

If you include "Wire_slave.h" as the very first thing in the sketch it will pull in the libmaple slave i2c code and prevent any use of the normal Wire.h.

Slave mode is not yet included in Wire_slave.h, so the only examples that work are, so far,
`master_writer.ino` talking to `i2c_libmaple_slave.ino`

**Comment by rogerclarkmelbourne** [comment]
@lacklustrlabs 

Thanks for converting to a library

I'll try to find time at the weekend to build a test rig, i.e 2 boards connected together

**Comment by rogerclarkmelbourne** [comment]
The status of this PR on github seems to be a bit confusing, it says that its been merged but there still seem to be files listed to be merged.

@lacklustrlabs  can you tell me what the status of this is ?

**Comment by stevstrong** [comment]
Will this conflict with #409 ?

**Comment by stevstrong2** [comment]
I think this can be closed since #409 already provided I2C slave funtionality.

**Comment by stevstrong** [comment]
I close this as we already have the I2C slave lib (thank to Donna).

**Pull request closed without merging**
