### PR TITLE
Code cleanup and removed compiler warnings about while loops

### PR DESCRIPTION
**Pull request by saloid**

### CODE REVIEW

**Comment by stevstrong** [comment]
Looks good. In addition I would move the function to the beginning of the file where it is declared.

**Comment by saloid** [comment]
I am trying to follow code style - so it near other same functions, which are declared on top and defined at bottom.

**Comment by stevstrong** [comment]
Except that this is an inline function.
Have you checked that it is really compiled as such?

**Comment by saloid** [comment]
I have compiled with and without "inline" - so file

**Comment by stevstrong** [comment]
Try to move the whole inline function (without any other declarations) to the header file, then it will be for sure inlined.

**Comment by stevstrong** [comment]
I merged this as it seems to make the core more readable.
Another commit of SPI.h will follow to complete this PR.

**Pull request merged**
