### PR TITLE
Update boards.txt

### PR DESCRIPTION
**Pull request by Testato**
- Exluded CCM Ram

### CODE REVIEW

**Comment by victorpv** [comment]
Thanks Testato, I think it makes more sense like that.
On another note, there is a discussion going on in the forum about the CCM, in case you want to discuss that subject there.
There are some options to use CCM. It has some limitations (no DMA and no code), so I'm not sure we will all come to an agreement about it, but perhaps we can find a way to conditionally use it depending on options or something.

**Comment by rogerclarkmelbourne** [comment]
There is now a merge conflict with @stevstrong latest changes to F4 boards.txt, can someone investigate?

**Comment by Testato** [comment]
Solved

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
