### PR TITLE
Update board.h

### PR DESCRIPTION
**Pull request by hhdang**
Pins Update

### CODE REVIEW

**Comment by hhdang** [comment]
STM32F103ZE's Pins is A to G，111 Pins(except BOOT1)

**Comment by rogerclarkmelbourne** [comment]
Can you give more details on what this PR does and why ?

I see you removed "PD2".

Whats wrong with that pin ?

**Comment by hhdang** [comment]
No,I removed "PB2", it reference to STM32F103VC's board.h,that file removed "PB2" because of BOOT1

**Comment by rogerclarkmelbourne** [comment]
There is no reason to do that.

You can use PB2 for normal GPIO operation.


You just cant use it while boot0 is Low.

The Maple mini board uses it just fine as a normal pin 

see

https://github.com/leaflabs/maplemini/blob/master/maplemini.pdf

**Comment by hhdang** [comment]
OK, I forked your old version,  your newest STM32F103V's board.h has added "PB2"。

**Comment by rogerclarkmelbourne** [comment]
No sure why you'd want to have a fork where its removed.

If you don't want to use PB2, simply don't use it in your code

**Comment by hhdang** [comment]
haha, i'm a junior github user, i forget to fetch the newest code before pull.

**Pull request closed without merging**
