### PR TITLE
Define defaults build.flags

### PR DESCRIPTION
**Pull request by fpistm**
Useful when using arduino-builder

### CODE REVIEW

**Comment by stevstrong** [comment]
Aren't the optimization flags specified over an Arduino IDE option (see boards.txt)?
If so, why to specify it here and then to overrule it?

**Comment by fpistm** [comment]
Yes, thanks the Arduino IDE but for example when using arduino-builder (or arduinon CLI), this require to fully specified this. while it is the defaults value.
You're right that it's overrule. So the boards.txt could be clean a little, I've updated my commit.

**Comment by stevstrong** [comment]
+1

**Comment by rogerclarkmelbourne** [comment]
I tested this and it seems OK on the Maple mini.

Note. I had to manually merge F1 platform.txt because of a conflict with the HID bootloader.
(I'm not sure why git thought there was a conflict, possibly just the CRLF line ending on the bootloader "pattern"

**Pull request merged**
