### PR TITLE
recompile upload-reset for 64-bit systems

### PR DESCRIPTION
**Pull request by midnight-wonderer**
The precompiled upload-reset in linux64 is actually for 32-bit systems.

Try `file ./tools/linux64/upload-reset` and you'll get
~~~
ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=dc8dc5ad6de94179a9d534b1a34aeb6d906640b1, not stripped
~~~

That's why it does not work.

Recompiled with
~~~
gcc -o ./upload-reset -O3 ./src/upload-reset/upload-reset.c
~~~

### CODE REVIEW

**Comment by midnight-wonderer** [comment]
Probably related:
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/454

Credit:
https://community.platformio.org/t/upload-reset-no-such-file-or-directory/8656/5

**Comment by stevstrong** [comment]
Can anyone else test it? I don't have Linux.

**Comment by ddrown** [comment]
Testing on Ubuntu 20.04.1 and Fedora 32, this looks good.

I verified:
* Ubuntu gcc used compiles the exact same binary
* strace output from the 32 bit and 64 bit binaries have the exact same ioctl/sleep sequences to manipulate the serial port

+1 from me

**Comment by stevstrong** [comment]
I have no Linux distro where to check, but I trust the two testers, so I will merge this.
It can be reopened if problems occur.

**Pull request merged**
