### PR TITLE
Phonog patch 1

### PR DESCRIPTION
**Pull request by Phonog**
This is an attempt to submit the HardwareCAN library plus the 3 files that must be changed in the core and the system to allow the library to communicate with the system.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'm still testing / merging and committing a backlog of PR's

I'll get to this one when I can.

**Comment by bilbolodz** [comment]
Any news about merging these patch?

**Comment by Phonog** [comment]
Bilbolodz, please ask Roger Clark on http://www.stm32duino.com for him to merge my contribution to the trunk. Your question only reached me. Thanks anyway for your interest.

**Comment by rogerclarkmelbourne** [comment]
http://www.stm32duino.com/posting.php?mode=post&f=53

**Comment by rogerclarkmelbourne** [comment]
BTW. Does this change any files apart from the CAN Hardware library files.

e.g. does it change any core files ?

(It didn't look like it does, but I may have missed something)

**Comment by Phonog** [comment]
Speaking of my change of yesterday, only the library files are altered.
I have downloaded the full package you recently updated, and I checked that the three core files that require a change to be compatible with the HardwareCAN library did not change since my original upload. Thus updating the package is straightforward : just apply to the three core files the changes described in the file changes.h of the example file.

**Comment by megadrifter** [comment]
I've made PR with core files change. Please check.

**Comment by Phonog** [comment]
@megadrifter 
Thanks for doing the changes. I checked all the files that i am concerned with, and found only two changes that are still to do :

1---------------------- (documentation only)
In file STM32F1/libraries/HardwareCAN/examples/HardwareCANexample/Changes.h, line 34 reads
+{ return 1 ; }      // Dummy ISR 
please change to 
+{ return 0 ; }      // Dummy ISR 

2----------------------- (useless file)
file can.temp.c should be removed. It was a security copy of can.c.
Thanks again.

**Pull request closed without merging**
