### PR TITLE
fix LeafLab code for spi_config_gpios() 

### PR DESCRIPTION
**Pull request by martinayotte**
fix LeafLab code for spi_config_gpios() which can't tolerate different GPIOs port for SPI pins when using alternate pinout such as : 
#define BOARD_SPI2_NSS_PIN      Port2Pin('B',11)
#define BOARD_SPI2_MOSI_PIN     Port2Pin('C',3)
#define BOARD_SPI2_MISO_PIN     Port2Pin('C',2)
#define BOARD_SPI2_SCK_PIN      Port2Pin('B',10)

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks Martin

You have changed more files than I thought you'd need to.

What were those BPK files ?

Anyway.....

I'll add it to my To Do list for the F103 but @stevestrong is currently making some changes in associated areas, so I may need to wait for him to finish before I change anything

Thanks again

Roger

**Comment by martinayotte** [comment]
Hi Roger,
The BKP and RCC changes are not related with the SPI, but as mentioned in it separate commit, they were missing in my previous contribution of RTClock committed few days ago, without them, RTC code won't compile. The BKP is old code from LeafLab, but they were put aside for unknown reason, files were renamed brk.c.xxx and brk.h.xxx and corresponding clocks commented in rrc.h/rrc.c, I've reactivated things.
The SPI refactoring was done a distinct commit, so for history, it should be fine and understandable.

**Comment by rogerclarkmelbourne** [comment]
Hi Martin

OK

Its hard to tell in GitHub which change relates to what 

Thanks

Roger

**Comment by stevstrong** [comment]
Hi,
don't wait for me, e1b85b7 can be integrated for F103, too, as it is. I will then merge to my local repo.

**Pull request merged**
