### PR TITLE
Fix Serial numbers shifting when no SERIAL_USB 

### PR DESCRIPTION
**Pull request by saloid**
#655

### CODE REVIEW

**Comment by saloid** [comment]
Not tested - need somebody to test.

**Comment by stevstrong** [comment]
I have tested this for several examples and it builds error free.

**Comment by stevstrong** [comment]
@saloid 
could you please remove from this PR the changes related to in-lining some functions, being not relevant to serial definitions?

**Comment by saloid** [comment]
OK, I will revert inlines and open for them separate PR, right?

**Comment by stevstrong** [comment]
Are the inlines needed for the serial stuff?

**Comment by saloid** [comment]
I don't think so, they are even not from my commits. I have pulled them from main repo before making any changes in my fork (to be synced with original).

**Comment by stevstrong** [comment]
Ah, ok, I will then check this as it is.

**Pull request merged**
