### PR TITLE
F1 SDIO first version

### PR DESCRIPTION
**Pull request by victorpv**
To enable 4bit wide mode, uncomment from this line to line 496:
https://github.com/victorpv/Arduino_STM32/blob/patch-3/STM32F1/libraries/SDIO/SdioF1.cpp#L491

In line 513 in that same file you can adjust the speed. I have tested from 1Mhz (1000) up, but with my card reader doesn't seem to work fine past 1Mhz. I have checked with a logic analyzer and the frequencies look right,

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Tried to compile for my F103Z board and I get

BOARD_SDIO_D0

So i guess that definition is missing 

Which board did you select ?

**Comment by victorpv** [comment]
I submited the change only for 1 board, the generic 103r, didn't want to make changes to a ton of files until we have the final code, you can add the same lines to the Z:
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/339/files#diff-010bbb9d6bf0c10efd6e8415cb230b28

**Comment by victorpv** [comment]
I bet you can also compile for the R, and upload to the Z and should work.

**Comment by rogerclarkmelbourne** [comment]
Hi Victor

OK. The Z is a superset of the R so I think it should work.

I'll try building it later

BTW. Do you have any example sketch code to try this with ?

Because at the moment all I'd be able to confirm is that it compiles for me.

Or did you post a sketch to the forum ?

Ideally we'd add an example of how to use this as well as the changes to the core

**Comment by victorpv** [comment]
I was using the Bench.ino example from the latest SDFat. The use is similar to what Steve did with the F4 (copying it here with the changes for F1):
- get the SdFat lib from https://github.com/greiman/SdFat
- insert into line 164 of SdFatConfig:
CODE: SELECT ALL
#elif defined(__STM32F1__)
#define ENABLE_SDIO_CLASS 1
- use in example sketches
CODE: SELECT ALL
#include "SdioF1.h" // instead of #include "SdFat"

**Comment by rogerclarkmelbourne** [comment]
@victorpv 

OK.

I'll try to install the latest SDFat etc, later today

**Comment by rogerclarkmelbourne** [comment]
In bench.ino, do I need to change

// Set USE_SDIO to zero for SPI card access. 
#define USE_SDIO 0

to

// Set USE_SDIO to zero for SPI card access. 
#define USE_SDIO 1

??

But if I do that I get

SDIO_bench:39: error: 'SdFatSdioEX' does not name a type

:-(

**Comment by rogerclarkmelbourne** [comment]
I'm going to merge this, as its mainly additional files and won't have any negative effects to the F103R by adding those defines.

Then perhaps a few more people can try it. ;-)

**Comment by victorpv** [comment]
Hopefully so :)
I need to order a new 103 board that should have the sdio with all pins connected, hopefully that will help me test further too.

**Comment by cheeta1** [comment]
hi there @rogerclarkmelbourne   did you managed to run th SDfat library with SDIO on stm32f103Z? 
also can you answer your own question given below

"
In bench.ino, do I need to change

// Set USE_SDIO to zero for SPI card access.
#define USE_SDIO 0

to

// Set USE_SDIO to zero for SPI card access.
#define USE_SDIO 1

??

But if I do that I get

SDIO_bench:39: error: 'SdFatSdioEX' does not name a type

:-(

"

thanks for the awesome library.

**Pull request merged**
