### PR TITLE
Base Adafruit_GFX_AS on Adafruit_GFX, keeping only the additions in a derived class.

### PR DESCRIPTION
**Pull request by tfry-git**
The point of this is to make drivers based on Adafruit_GFX_AS compatible with Adafruit_GFX,
without breaking existing code written for Adafruit_GFX_AS.

See also http://stm32duino.com/viewtopic.php?f=9&t=3352

### CODE REVIEW

**Comment by ImpulseAdventure** [comment]
For reference, the PR worked fine in my tests: http://stm32duino.com/viewtopic.php?f=9&t=3352#p42721

**Comment by rogerclarkmelbourne** [comment]
OK

I know @victorpv  was also testing, so I'll ask in the forum to find his opinion

**Comment by NickNifontov** [comment]
'class Adafruit_ILI9341_STM' has no member named 'getTextBounds'

'class Adafruit_ILI9341_STM' has no member named 'getCursorY'

**Comment by rogerclarkmelbourne** [comment]
This is strange.

I thought I just merged this.

**Pull request merged**
