### PR TITLE
Enable tamper output to RTC calibration

### PR DESCRIPTION
**Pull request by hyperion11**
add two functions.
void rtc_enable_calibration(void);
void rtc_disable_calibration(void);

useful rtc calibration. After enabling on PC13 will be found LSE/64 freq.
For check i disable internal led blinking on PC13. I do not know what will happen if enabled TAMPER output to PC13 and digitalwrite to PC13. And dont't want try to check it :)
details about calibration
http://www.st.com/resource/en/application_note/cd00167326.pdf
in Russian
http://uc.org.ru/node/27
check with logic analyser freq
work fine

image

### CODE REVIEW

**Comment by hyperion11** [comment]
sorry for large numbers of corrections :) Still newbie in github and programming :)

**Comment by rogerclarkmelbourne** [comment]
The one potential problem is this line 

RCC_BASE->BDCR |= RCC_BDCR_RTCSEL;

It will apply all the time, not just when using the calibration functions you added


What does this change do ?

**Comment by hyperion11** [comment]
I remove this. Adding this was mistake, but with this string work fine :) BTW better without it.

**Comment by rogerclarkmelbourne** [comment]
OK. (LOL)  

Do you mean it works better without this ?

**Comment by hyperion11** [comment]
I think it works equally :)
I upload test code with this string. It work normal. But when i google this string, after your comment, i found that i not correct understand what it doing.

**Comment by rogerclarkmelbourne** [comment]
OK.

Less risk if we don't have that line

BTW. Not sure why, but gitub now tells me there is merge conflict with 

STM32F1/libraries/RTClock/examples/BluePill-RTClock-test/BluePill-RTClock-test.ino

Did you change something else ?

**Comment by rogerclarkmelbourne** [comment]
This now has conflicts which I don't know how to resolve

**Comment by rogerclarkmelbourne** [comment]
I'll close this, but please re-open when the conflicts have been resolved

**Pull request closed without merging**
