### PR TITLE
Corrected ADC_CR2_TSVREFE bit definition

### PR DESCRIPTION
**Pull request by stevstrong**
This change bit definition is inline with the user manual.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Steve

I think I need to do create a "release" before I can merge development back into master as development removes support for IDE 1.6.5 to fix the warnings about recipies in 1.6.9

I was going to create a new branch for this (from master), so it gives people other than me, a chance to test this

BTW. Do you have an example that uses 16 bit transfers ?

I recall investigating 16 bit transfers a while ago, but I don't think they worked for me (which is I presume what this fixes ;-)

**Comment by stevstrong** [comment]
Hi Roger,
I posted here [http://www.stm32duino.com/viewtopic.php?f=9&t=891&p=15048#p13036](url) a code snippet, but it looks like I have to send you further PR for that example to work (which would allow the SPI slave initialization). Do you think that it makes sense?

**Comment by rogerclarkmelbourne** [comment]
PR's are  a bit strange, I think if you do another one after updating your repo, it will probably merge it with this one

**Comment by stevstrong** [comment]
Hm, as I am a newbie regarding github, anything is possible :)
 I did an update yesterday, will check it again, and do another PR.

**Comment by rogerclarkmelbourne** [comment]
I'm not much of an expert at sending PR's

I'm more of an expert at receiving them ;-)

**Comment by stevstrong** [comment]
I guess, I still have to write a clean example for 16 bit mode and slave mode, maybe both in one...

**Comment by rogerclarkmelbourne** [comment]
Thanks Steve

No rush.

**Comment by RickKimball** [comment]
You should change the name of this issue ... it is 99% about something other than ADC_CR2_TSVREFE and 1% about it.

**Comment by RickKimball** [comment]
@stevstrong  why don't you create a new issue about the SPI and put the changes into that issue with a different pull request

**Comment by stevstrong** [comment]
> why don't you create a new issue about the SPI and put the changes into that issue with a different pull request
because I don't know how it goes

**Comment by rogerclarkmelbourne** [comment]
I've not forgotten about this. Its just there has been a lot to do with the new STM core

I may just pull it into a separate branch and test on my ILI9341 display (which uses SPI) and if it works I may as well merge the PR into Master

**Comment by rogerclarkmelbourne** [comment]
Steve
I finally got around to testing this, and I get compile issues straight away ;-(

call of overloaded 'transfer(int)' is ambiguous

I just ran the stm32_graphicstest from the examples

Looking at why this is happening, it looks like you have two functions called transfer(), one for 8 bit and one for 16 bit

But looking at the arduino reference for this,

https://www.arduino.cc/en/Reference/SPITransfer

 the 16 bit transfer should be 

```receivedVal16 = SPI.transfer16(val16)

I'll change your code and push your branch to the sever  so you can see if that change is acceptable

**Comment by rogerclarkmelbourne** [comment]
OK. My updated version of your code is here

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/stevstrong-master

But it won't merge with master because it clashes with https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/f9301a6acf4290f56ffc28e7785a681655426fa2

which I've already committed

Can you pull my branch of your repo and see if your changes to USB are compatible

Thanks

**Comment by rogerclarkmelbourne** [comment]
Is this stable now ?

**Comment by stevstrong** [comment]
Yes, sorry, I am totally layman here on github, but it seems that finally managed to merge your branch.

**Comment by rogerclarkmelbourne** [comment]
OK
I'll try pulling into the branch I made for your PR

Note. I had to change the SPI.transfer to SPI.transfer16 to fix the function overloading issue, so I'll need to see if that effects the merge

**Comment by rogerclarkmelbourne** [comment]
Seemed to merge into your branch OK

SPI.transfer16 still seemed to be there after the merge, as did the new JLink code I added yesterday and also the PR for ADC seemed to be still merged

So... I guess we need people to test this now

**Pull request merged**
