### PR TITLE
Fixed a few STM32F1 compiler warnings..

### PR DESCRIPTION
**Pull request by lacklustrlabs**
..by adding gcc specific tags e.g. `__attribute__((unused))`
~~Also replaced tab with spaces in some files.~~

### CODE REVIEW

**Comment by stevstrong** [comment]
I see too many additional changes.
Would it be possible to have **only** the unused attribute?

**Comment by stevstrong** [comment]
Your changes are conflicting some recent ones.

**Comment by rogerclarkmelbourne** [comment]
I will leave this open as a reminder, but the PR is now so far out of date I would not be able to merge it

**Comment by lacklustrlabs** [comment]
I tried to resolve the conflicts, but I have to admit that my git-fu is too weak.
It will be much easier for me to recreate the PR from scratch.
I'll create a separate PR for `__attribute__((unused))` and the signed/unsigned test warnings, if you think it's worth the effort.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request closed without merging**
