### PR TITLE
STM32F4 development

### PR DESCRIPTION
**Pull request by stevstrong**
- added generic F4 board variant
- removed F1 and F2 files/defines
- resolved include headers - now libraries are detected within sketches
- reworked + added new GPIO access functions
- moved and size-optimized PIN_MAP in flash
- SPI improvements: optimized block read + added DMA

### CODE REVIEW

**Comment by stevstrong** [comment]
Hi Roger,
I think I managed to sum up all my F4-related changes so far in this PR, so this overrides #267 .
Would be nice if you (or someone else) could test it.
It works nicely for me, see http://www.stm32duino.com/viewtopic.php?f=39&t=2054&p=27688#p27770.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks

Lots of changes. ;-) I think I'll need to contact Martin, as he is usually the most active F4 user.

I have a STM F4 Discovery board as well as the SeedStudio ArchMax, and the Nucleo F446

However I'd need to test with the F4 discovery, and I don't have a test rig setup for that board where I can easily attach a display etc to test SPI.

**Comment by stevstrong** [comment]
Indeed lots of changes, but because no one was actually working on this area, I felt myself free to change things which did not work or had to be updated, and which I did not like :)
I just realize that I neglected everything else then generic F4, wanted to compile the SD bench for F4 disco and it failed.
So there will be more changes to come. I don't have any disco F4 board, but at least will make it to compile error free.
 Also, Arch Max has to be added as variant, which I can test.

**Comment by stevstrong** [comment]
Hi Roger, now other variants compile error free as well.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I've merged the PR as the changes were only to the F4 ;-)

**Comment by stevstrong** [comment]
Thanks, Roger, this simplifies a lot my local branch handling :)

**Comment by rogerclarkmelbourne** [comment]
No worries

**Pull request merged**
