### PR TITLE
Adding PB2 as in the Generic R and Z versions.

### PR DESCRIPTION
**Pull request by victorpv**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Looks OK.

I"m in the middle of looking at another PR at the moment, but this one should be easy and safe to merge, once I've processed the other one

**Comment by lacklustrlabs** [comment]
Maybe keep the 'PB2 == boot1' comment

**Comment by victorpv** [comment]
@lacklustrlabs after the enum?

**Comment by lacklustrlabs** [comment]
@victorpv I was thinking in the margin of the PIN_MAP (board.cpp), all kinds of useful pin info is written there.

**Comment by victorpv** [comment]
Ok, just added the comment there.

**Pull request merged**
