### PR TITLE
Update platform.txt - Reduces line length of build output message

### PR DESCRIPTION
**Pull request by stevstrong**
cosmetics: remove unnecessary blank space

Reduces line length of build output message.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Does this work on all platforms ?

e.g. Linux and Mac as well as PC?

**Comment by stevstrong** [comment]
I only removed some pointless spaces from the line, it should work for Linux and Mac, but I haven't tried.

**Comment by rogerclarkmelbourne** [comment]
OK. 
I thought perhaps you had split the line into 2 lines

**Comment by victorpv** [comment]
Looked at my local copy, and I see the bunch of spaces in Windows. Not sure what character code they are, and if it will show the same in linux, but definitely showing in Windows as just spaces, this change looks good to me.

**Pull request merged**
