### PR TITLE
Fixed missing return value.

### PR DESCRIPTION
**Pull request by GitMoDu**
Overloaded method was not returning the result.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

Looks like a mistake

However I'll need to test this to confirm there are no side effects of fixing it.

**Comment by rogerclarkmelbourne** [comment]
Thanks

Tested with a BMP280 using the I2C scanner and also the Adafruit BMP280 lib

Both worked fine.

**Comment by GitMoDu** [comment]
I'll test some other I2C devices in the meanwhile.

**Comment by rogerclarkmelbourne** [comment]
I think its fine.

Its now merged into the core.

I'm sure people will let me know if they have problems with it ;-)

**Pull request merged**
