### PR TITLE
Stm fft

### PR DESCRIPTION
**Pull request by victorpv**
STM's FFT functions in assembler. All 3 of STM ones, plus added a new 16bins one from modifying the 64bins one.
Does not change any other file.

### CODE REVIEW

**Comment by stevstrong** [comment]
Is there any documentation how to use them?

**Comment by victorpv** [comment]
I believe there was some other file from STM, I'll try to find it and add to the PR.

**Comment by victorpv** [comment]
Help file from STM added

**Comment by stevstrong** [comment]
Thanks, it seems I need to read a lot :)

**Comment by rogerclarkmelbourne** [comment]
Tested and merged.
Thanks

**Pull request merged**
