### PR TITLE
Fix case of spaces in path to linux tools directory

### PR DESCRIPTION
**Pull request by Quantalume**
Fix for issue #124

### CODE REVIEW

**Comment by Quantalume** [comment]
Change at line 20 unnecessary.

**Comment by rogerclarkmelbourne** [comment]
Hi @Quantalume 

I'm loosing track of what needs to be done and what doesnt.

Is the version now in the PR the one that works for you?

**Comment by Quantalume** [comment]
Yes, the version in the PR works for me. Thanks.

**Comment by rogerclarkmelbourne** [comment]
This change is now in the master and development branches.

Please retest against my repo if you have time.

**Pull request merged**
