### PR TITLE
Fix compilation with -std=gnu++11

### PR DESCRIPTION
**Pull request by tfry-git**
See https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/402

### CODE REVIEW

**Comment by lacklustrlabs** [comment]
I wonder if we really need the `#if __cplusplus >= 201103L` tests.
http://www.stm32duino.com/viewtopic.php?f=3&t=1241&p=38520#p38520

**Comment by tfry-git** [comment]
I suppose it depends which compilers we may still want to support. If we are all set to stick with C++11(or later) for good, a fix without standards version check is even more trivial. I don't mind if this request is rejected, I'd just like to get the issue fixed one way or another.

**Comment by stevstrong** [comment]
gnu11 was introduced without any fallback scenario.
So we don't need any ifdefs.

**Comment by tfry-git** [comment]
Next attempt: https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/407

(Seems I can change the target branch to merge to, but not the source branch to merge form in a PR)

**Pull request closed without merging**
