### PR TITLE
Ili9341 develop

### PR DESCRIPTION
**Pull request by stevstrong**
- cleanup non-STM32 relevant parts
- add possibility to pass an SPI object to begin
- added new function: void pushColors(void* buf, uint16_t nr_pixels);
- optimize DC and CS pin toggling
- updated graphics example

### CODE REVIEW

**Comment by stevstrong** [comment]
Ups, it seems that some not ILI9341 relevant changes also appeared here...
I think I will never learn how to make a clean PR, sorry. ;(

**Comment by rogerclarkmelbourne** [comment]
OK.

I'm not sure if you tried to remove the ILI9341 code, but it still looks like its in this PR

**Comment by rogerclarkmelbourne** [comment]
Whats the current status of this ?

**Comment by rogerclarkmelbourne** [comment]
Looks my latest commits prevent audio merging :-(

**Comment by stevstrong** [comment]
I have resolved some conflicts, the master had some new stuff which was not in my PR.
Now it should be possible to commit.

Unfortunately, this PR contains some additional F4 related stuff, but it also correct some input capture definitions for F1.
I would say it would make sense to have these in master.
I am working with these improvements for a couple of weeks now and had no problems so far.
But it would be good if someone else could also test it.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'll pull to a separate branch and see if my camera and graphics test code still works

**Comment by rogerclarkmelbourne** [comment]
I tried pulling this update and compiling the "graphicstest" from the examples in the Adafruit_ILI9341_STM library

But I get the following errors

```
D:\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Adafruit_ILI9341_STM\Adafruit_ILI9341_STM.cpp:62:6: error: prototype for 'void Adafruit_ILI9341_STM::begin(SPIClass&, uint32_t)' does not match any in class 'Adafruit_ILI9341_STM'

 void Adafruit_ILI9341_STM::begin(SPIClass & spi, uint32_t freq)

      ^

In file included from D:\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Adafruit_ILI9341_STM\Adafruit_ILI9341_STM.cpp:6:0:

D:\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.h:107:12: error: candidates are: void Adafruit_ILI9341_STM::begin()

   void     begin(void) { begin(SPI); }

            ^

D:\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\Adafruit_ILI9341_STM/Adafruit_ILI9341_STM.h:106:12: error:                 void Adafruit_ILI9341_STM::begin(SPIClass&)

   void     begin(SPIClass & spi);
```

**Comment by stevstrong** [comment]
I will have a look on this.

**Comment by stevstrong** [comment]
I just fixed the missing prototype error message.
It should compile and run now.
My test output:
```
Benchmark                Time (microseconds)
Screen fill              170779
Text                     31442
Lines                    158151
Horiz/Vert Lines         15413
Rectangles (outline)     10554
Rectangles (filled)      354928
Circles (filled)         97001
Circles (outline)        125307
Triangles (outline)      35618
Triangles (filled)       145196
Rounded rects (outline)  45006
Rounded rects (filled)   405601
```

**Comment by rogerclarkmelbourne** [comment]
OK. I'll try pulling it locally and see if it works for me

**Comment by lacklustrlabs** [comment]
I know nothing about stm32_f407 but isn't it confusing if `portSetRegister(pin)` and  `portClearRegister(pin)` points to the same address? Yeah, i suspect MSW is reset and LSW is clear, but the other variants points directly to the set / reset word.

```
 #define portSetRegister(pin)		( &(PIN_MAP[pin].gpio_device->regs->BSRR) )
-#define portClearRegister(pin)		( &(PIN_MAP[pin].gpio_device->regs->BRR) )
+#define portClearRegister(pin)		( &(PIN_MAP[pin].gpio_device->regs->BSRR) )
```

**Comment by stevstrong** [comment]
Which variants did you mean? Or you mean other STM32 families?
This is a rather a feature than a bug.
F1 has two different resisters, and can only write the BSRR and BRR registers in two different steps.
While F4 has only one and thus can write in one shot both set and reset bits, which is advantageous.
Of course, you could force to write separately the set and clear bits similar to F1, but i doubt this would be efficient.
And anyway, there are several other differences between F1 and F4, this is only one of them which you should be aware of.

**Comment by stevstrong** [comment]
This PR includes unfortunately F4 related changes, which is not desired.
If wanted, I could eventually remove them and send another PR only for F4 related stuff.
However, my github activity history so far shows that I am somehow not able to send clean PRs...

**Comment by lacklustrlabs** [comment]
One way to make `portSetRegister()` and `portClearRegister()`API compatible across all variants (including F1) would be change the return type to `uint16_t*` across all variants and point to the correct bits of BSRR on F4.
But then we'll lose the  ability to set and reset in one atomic operation (using this API)

**Comment by lacklustrlabs** [comment]
Regarding git, switching over to [smartgit](http://www.syntevo.com/smartgit/) or [sourcetree](https://www.atlassian.com/) (on mac) made my life so much easier.

**Comment by rogerclarkmelbourne** [comment]
Yikes

This one has been superseded a lot.

I will close it.

Please re-open if it still needs to be merged and no longer has merge conflicts

**Pull request closed without merging**
