### PR TITLE
Update boards.txt

### PR DESCRIPTION
**Pull request by Testato**
PR for issue https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/200

- replaced `upload.flash.maximum_size` and `upload.ram.maximum_size` by the new arduino standard `upload.maximum_size` and `upload.maximum_data_size`
- corrected Flash and Ram value
- Tested by builded every MCU on every Variant

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
http://www.stm32duino.com/posting.php?mode=post&f=53

**Comment by Testato** [comment]
the link is not working,
i see you merged my first of three  PR. Is there some problem with the other two ?

**Comment by Testato** [comment]
link not working

**Comment by stevstrong** [comment]
Correct link: http://www.stm32duino.com/viewtopic.php?f=53&t=2290

**Comment by rogerclarkmelbourne** [comment]
@stevstrong 

Thanks. I was cutting and pasting many links, I think I got out of sync

**Comment by stevstrong** [comment]
I see low risk (F4 related) and big benefit.

**Comment by victorpv** [comment]
Looks good to me too. Seems like Arduino changed those labels, so it's good to change them, and some sizes were wrong and look better now.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by victorpv** [comment]
@Testato the current linker scripts do not allocate anything to the CCM memory, so the MCU can't use it.
Reporting 192KB of available RAM when the MCU in fact can only use 128KB would not be appropiate. Unless you are planning to modify the linker scripts, it would be better to report the memory in those MCU as the normal RAM capacity excluding CCM.
Could you correct and resubmit?

**Comment by Testato** [comment]
@victorpv 
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/303

**Comment by victorpv** [comment]
Thanks Tetato. I think it makes more sense like that until a decission is made on how to use CCM and we make it usable.
There is a thread in the forum discussing on that if you want to join.

**Pull request merged**
