### PR TITLE
Set module

### PR DESCRIPTION
**Pull request by victorpv**
This is my branch with your setModule code, plus the DMA support for all ports.
I have not tested setModule, but I tested that declaring 2 objects still works perfectly fine, and I can use dmaSend in either one of them without an issue.
I am running sdfat in SPI1 and an ILI9163 in SPI2, both using DMA transfers in their respective channels.

I don't know how to pick individual files for a pull request, so don't accept this one to merge, but just pick the SPI.c and SPI.h files to update yours. The DMA controller and channel IDs all are taken now form _currentsetting and working, so I expect them to work when we change the pointer. 

I may have a chance to test it out with setModule over the weekend. If you make more changes please use these as a base so all the DMA changes are already applied.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Victor,

I'll need to pull this locally to a new branch and test it as github tells me it cant automatcially merge this as your repo is out of date :-(

Its showing changes to files that I have already changed,

I may end up having to manually just copy stuff across :-(

**Comment by victorpv** [comment]
go to my branch called setModule, and download SPI.c and SPI.h from that branch, that's all you need.
I sent the pull just to have it notify you, but it was also telling me I can't merge. I am way behind in my fork, but I can't resync until I finish the things I am changing and get stable, so I can save those changes, and then resync back to the master.

**Comment by rogerclarkmelbourne** [comment]
Hi Victor

OK. I'll do that. But I can't do it until later.

**Comment by rogerclarkmelbourne** [comment]
Victor,

I did the pull manually, by replacing my SPI.cpp and SPI.h with your versions, as I needed to do it incrementally with my setModule change.

So. I'll close this PR as its effectively been superseded.

**Pull request closed without merging**
