### PR TITLE
F4: merge all files from stevestrong master

### PR DESCRIPTION
**Pull request by stevstrong**
Roger, this would bring the F4 part up to date with my current repo.
Yes, I know, there are a lot of changes, but in any case I intend to actively support this, as it will also flow back to my repo.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I will pull locally and merge

**Comment by rogerclarkmelbourne** [comment]
Thanks.  I tested locally and it compiled OK.

I think I can safely delete the stevestrong_F4_merge branch in github

**Comment by ag88** [comment]
hi steve, roger, 
how about merge the F3 core as well?

**Comment by rogerclarkmelbourne** [comment]
The F3 core in my repo was essentially just an archive to prevent it being lost forever.

But if Steve's version is function, please feel free to merge it into my repo

**Pull request merged**
