### PR TITLE
Fix interrupt race condition in usb_cdcacm_rx() and vcomDataRxCb()

### PR DESCRIPTION
**Pull request by Rasmusfk**
This patches an interrupt race condition usb_cdcacm_rx() and vcomDataRxCb(), which only occurred during high-bandwidth usb-to-serial transmission.

### CODE REVIEW

**Comment by jaretburkett** [comment]
There are two PRs that will conflict. I have tested both Stevstrong's and Rasmusfk's. They both completly solve both issues in the CDC core and use two different methods to solve them. I have tested with multiple tests from images, single bytes, and readbytes into a buffer. The one by stevstrong is a little faster on my read bytes testing. Stevstrong's version averages ~316 kBps on reads and Rasmusfk's version averages ~ 278 kBps on reads. Both are improvements on the current version which is only ~242 kBps. I am running tests for 2 different image to tft programs I have, as well as the test files provided at [PJRC http://www.pjrc.com/teensy/benchmark_usb_serial_receive.html](http://www.pjrc.com/teensy/benchmark_usb_serial_receive.html). I think others should run tests on both (I am testing in a linux environment), but my tests lead me to recommend Stevstrong's version. (I am posting this on both PRs.)

**Comment by Rasmusfk** [comment]
Please note that my PR solves the race condition, I'm not convinced that Stevstrong's does, though I might be wrong.

**Comment by stevstrong** [comment]
This is the classical way to resolve race condition, disable the involved interrupt.
The drawback is, you disable thereby also the Tx channel. So full duplex will suffer because of this.
My version is one which i was using successfully using during several years i was working professionally in the SoC field. I don't want to defend my work, but i am confident it shall work. And according to my and Jaret's test, it does work.
Additionally, the Tx channel is also improved with my PR.
But it is up to Roger to decide which version is he happy with.
If this fix would have come before i start investigating the problem, i would may be happy with it.

**Comment by Rasmusfk** [comment]
If stevstrong's version doesn't have any race condition, I think we should go with that - I've tried it, and it works for me, and the tx buf change is a nice speedup.

Unrelated to the race thing: Would it be an idea dynamically allocate the rx/tx buffers in the USBSerial::begin() method, so that programs that doesn't need usbserial can save the buffer memory?

**Pull request closed without merging**
