### PR TITLE
To use STM32ADC in continuous mode triggered by an internal timer

### PR DESCRIPTION
**Pull request by syfre**
No sure for the compile error in util_adc.c but ADC_CR2_TSEREFE don't exists

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I'll need to get this tested before I can merge the PR

**Comment by victorpv** [comment]
There is a thread about ADC_CR2_TSEREFE, apparently was a flag that was named wrong and it was corrected last year, that's why it does not exist any more:
http://www.stm32duino.com/viewtopic.php?t=1317&start=20

So renaming that to TSV... is the right thing to do, since looks like that was just 1 miss from last time.

**Comment by rogerclarkmelbourne** [comment]
@victorpv 

Thanks

What about the change 

cr2 |= ADC_CR2_EXTTRIG;

?

**Comment by stevstrong** [comment]
`cr2 |= ADC_CR2_EXTTRIG;`
is needed in order to select the external event which triggers the ADC via EXTSEL.
Looks fine for me.

**Comment by rogerclarkmelbourne** [comment]
OK. I will merge...

Thanks

**Pull request merged**
