### PR TITLE
Fix for SREG error - with this flow sensor is working

### PR DESCRIPTION
**Pull request by goran-mahovlic**
http://www.stm32duino.com/viewtopic.php?f=27&t=1167&sid=aba6dee79a24c8ad667381a999c4c08c

https://github.com/sekdiy/FlowMeter

Other sensors that are using SREG will probably work to. 
When tested more you can add it to F3 and F4 boards.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Looks OK. But I need to check blink etc compiles OK

**Comment by rogerclarkmelbourne** [comment]
Wont compile if you include SPI.h :-(

**Comment by goran-mahovlic** [comment]
ok, I will check

tnx

**Comment by victorpv** [comment]
There is another pull including this pinToInterrupt function, but does it a different way.
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/225

I think would be positive if one of you post in the forum in stm32duino  a new thread about this to collect all the input and submit a single solution.

**Comment by rogerclarkmelbourne** [comment]
http://www.stm32duino.com/posting.php?mode=post&f=53

**Comment by rogerclarkmelbourne** [comment]
Whats the status of this?

Looks like no one uses it etc so perhaps I should close this due to lack of interest ???

**Comment by goran-mahovlic** [comment]
I did try now and will close it SREG error does not exist any more. 
And to fix sei() cli() error we just need to add  
#define sei() interrupts();
#define cli() noInterrupts();
at the end of wirish.h

**Pull request closed without merging**
