### PR TITLE
Fix to delayMicroseconds(0) bug

### PR DESCRIPTION
**Pull request by gioblu**
Ciao @rogerclarkmelbourne here is the fix as you requested https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/531

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'll need to pull locally and test before I can merge.
I do this even for seemingly simple PR's as I had problems in the past with some PR's not compiling because of typos etc

**Comment by gioblu** [comment]
Sure, no problem with have temporarily patched where needed.
I will wait for this pr to be closed to delete the patch :)
Thank you

**Comment by rogerclarkmelbourne** [comment]
I'd need to check what happens on the AVR Arduino.

We can potentially compensate for the number of clock cycles taken for the if statement, but that code should probably be written in assembler to guarantee that we know how many cycles that would be.

It looks like there is already a hack where the value is decremented to account for the function call overhead

```
    /* fudge for function call overhead  */
us--;
```

It looks like the official Arduino checks for zero

https://github.com/arduino/ArduinoCore-samd/blob/395695b0008765e18fee32e0214c9db53fb6c097/cores/arduino/delay.h#L66-L69

And does not seem to compensate for it.


Looking in more detail, the code also has this

` us *= STM32_DELAY_US_MULT;
`
Which is a bit alarming, because multiplication is slow unless the value is power of 2

**Comment by gioblu** [comment]
Ciao @rogerclarkmelbourne I agree with you about the multiplication issue.

**Comment by rogerclarkmelbourne** [comment]
I pushed my own fix, which is semantically different but functionally the same

NOTE. I know this adds a small additional delay, but this function is not highly accurate.

If someone wants to write a more accurate version please feel free to send a PR

**Comment by rogerclarkmelbourne** [comment]
BTW.
If you notice an issue with the timing we could possibly change the line that does 

`us--;`

to 

`us -=2;`

**Comment by stevstrong** [comment]
I am not sure if that `us -= 2;` would bring improvement, because what happens if us = 1?

**Comment by rogerclarkmelbourne** [comment]
Steve

Thats a good point.

I think we'll need to leave it as it is, as I don't think its ever been that accurate.

**Comment by stevstrong** [comment]
I agree.

**Pull request closed without merging**
