### PR TITLE
__io is replaced by the more correct __IO

### PR DESCRIPTION
**Pull request by aster94**
please see:
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/422
http://www.stm32duino.com/viewtopic.php?f=2&p=39999#p39999

[i also added some color highlight in keywords.txt]

### CODE REVIEW

**Comment by lacklustrlabs** [comment]
Why are there .exe and .dll files in there?

**Comment by rogerclarkmelbourne** [comment]
@lacklustrlabs 

I agree the exe's etc should not be in the PR.

I had another PR which had some exe's which seemed to have been something to do with the unix permissions

I could not merge that PR either, and had to manually merge the files that really needed to be changed

**Comment by aster94** [comment]
I must have done some error with git, i am not very proficient with it
Tomorrow i will edit the PR and fix them

**Comment by rogerclarkmelbourne** [comment]
No worries.  Git does strange things all the time.

Sometimes I have to rename the whole folder and clone again from the server, and then copy the files which have actually changed, however in this case as you have already pushed back to GitHub, you'd somehow need to get the exe's again and then push again and somehow update the PR (perhaps make a new PR)

You are not the only one who has problems like this ;-)

BTW. If all you did was a global search and replace on all c,cpp and h files for _IO and replace with __IO, I can easily do that in Notepad++ on Windows and perhaps make my own branch for this ??

**Comment by aster94** [comment]
@rogerclarkmelbourne @lacklustrlabs I am reading only now after removing my guilty files, anyway now this PR doesn't change any .dd and .exe files

P.S: im sure that i didn't modified those files, is it possible that uploading a few sketches with the arduino IDE get them modified?

**Comment by stevstrong** [comment]
This does not change F4 files, right?

**Comment by aster94** [comment]
this does change F1,2,3,4
shouldn't i put them?

**Comment by stevstrong** [comment]
I cannot see any F4 file in the changed file list.

**Comment by stevstrong** [comment]
Ups, sorry, my browser seems to play nuts. I see now all files.

**Comment by aster94** [comment]
never mind steve! 
if someone is wondering why there are 4 lines of difference between the add and delete, this is for "keywords.txt"
+1,256 −1,252  Files changed 118

**Comment by aster94** [comment]
thanks @victorpv, i know that there are many reason to don't do this change, on the other hand i am sure it will solve problems in the future
it is like for the wire library, imho it is better to be compliant with the arduino world and in this case also with the compiler

**Comment by rogerclarkmelbourne** [comment]
@victorpv 
Did you get around to trying this ?

I'm actually in favor of this, but I know it comes with a lot of risk

**Comment by victorpv** [comment]
Just tested with the mp3 software in the bluepill RET board. It uses the SDIO port and SPI2/I2S, both with DMA, so does a fair amount of register access. Works fine.
If I get a chance in the next few days will test with the WAV player that uses 2 SPI ports and a timer with DMA.

**Comment by rogerclarkmelbourne** [comment]
Thanks
Tested with a fairly complex application using 2 SPI devices and touch screen and also One Pulse timing and it compiled and ran fine

**Pull request merged**
