### PR TITLE
Add timer input capture for STM32F1

### PR DESCRIPTION
**Pull request by GIPdA**
Implements timer input capture on HardwareTimer class for STM32F1 boards.
Based on http://www.stm32duino.com/viewtopic.php?f=3&t=1029

### CODE REVIEW

**Comment by stevstrong** [comment]
Does [this patch](https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/f928acf19336e1d1f1ae146d3f9f9d8d18e19033) solve the PR?

**Comment by GIPdA** [comment]
I don't have any STM32 board on hand to test, but if it's working for you, it's good to me to close this PR.

**Comment by rogerclarkmelbourne** [comment]
I think I"ve already added this.

@stevstrong 
Can you confrim ?

**Comment by stevstrong** [comment]
Timer capture was added with the patch I linked in my previous message above.
So I think this PR is superfluous.
Unless the OP has something additional to comment.

**Comment by rogerclarkmelbourne** [comment]
I think this PR has been superseded. I will close it

**Pull request closed without merging**
