### PR TITLE
F1 usart   buffered interrupt based tx (static tx buffer)

### PR DESCRIPTION
**Pull request by edogaldo**
Minimal changes to implement buffered interrupt-based TX with static buffer.

### CODE REVIEW

**Comment by edogaldo** [comment]
Note: buffers sizes can be changed by adding USART_RX_BUF_SIZE and USART_TX_BUF_SIZE in boards.txt, i.e.:
```
[...]
mapleMini.build.cpu_flags=-DMCU_STM32F103CB -DSERIAL_USB -DUSART_RX_BUF_SIZE=64 -DUSART_TX_BUF_SIZE=32
[...]
genericSTM32F103V.menu.device_variant.STM32F103VC.build.cpu_flags=-DMCU_STM32F103VC -DUSART_RX_BUF_SIZE=96 -DUSART_TX_BUF_SIZE=96
[...]
genericSTM32F103V.menu.device_variant.STM32F103VD.build.cpu_flags=-DMCU_STM32F103VD -DUSART_RX_BUF_SIZE=128 -DUSART_TX_BUF_SIZE=128
[...]
genericSTM32F103V.menu.device_variant.STM32F103VE.build.cpu_flags=-DMCU_STM32F103VE -DUSART_RX_BUF_SIZE=128 -DUSART_TX_BUF_SIZE=128
[...]
```

**Comment by RickKimball** [comment]
+1

**Comment by RickKimball** [comment]
https://gist.github.com/piscisaureus/3342247 btw .. that is useful

**Comment by rogerclarkmelbourne** [comment]
Thanks...

I will pull and test this at the weekend

**Comment by rogerclarkmelbourne** [comment]
BTW
The Windows Github client doesn't like your branch name. I had to quote the branch name in order to get it to pull locally, and it also wouldn't accept the branch name, so I gave it a simpler one

**Comment by rogerclarkmelbourne** [comment]
OK.

I wrote this test sketch to confirm that the buffering was working

```
unsigned long ms,lastMillis;
char strBuf[16];

void setup() {
  Serial1.begin(1200);
}

void loop() {
  ms=millis();
  sprintf(strBuf,"Test %d\n",ms-lastMillis);
  lastMillis=ms;
  Serial1.print(strBuf);
  delay(50);
}```

If I run this sketch using the existing code I get the following output

```
Test 0
Test 100
Test 108
Test 108
Test 109
Test 108
Test 108
Test 109
Test 108
Test 108
```

Using the Serial buffer I get these results

```
Test 0
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 50
Test 59
Test 66
Test 67
Test 67
Test 66
```

In the second set of results the buffer is not able to write to the HW serial device as fast as its being written to by the code, so after approx 30 write the buffer is full and the write time goes up to between 66 and 67ms

The old code was the same speed all the time (100ms) - this is consistent with waiting for each char to be written individually.

So I will push the branch SerialTXBuffer to the repo.

I will see if anyone on the forum wants to test it, and if I don't have any bug reports in the next few days I'll merge into master

Thanks

Roger

**Comment by edogaldo** [comment]
Just want to highlight in your code you compute also the 50 ms delay, if you cut it you have a better perception of the response time improvement brought by the buffered tx.

Best, E.

**Comment by RickKimball** [comment]
Is this code supposed to be in that new branch you asked everyone to test?

**Comment by rogerclarkmelbourne** [comment]
Rick

I did a loacl pull to the new branch and i thought I had pushed the changes to the new branch, as it got created on github, but perhaps something failed,

I will double check.

**Comment by rogerclarkmelbourne** [comment]
Rick

Are you looking in the correct branch ?

https://github.com/rogerclarkmelbourne/Arduino_STM32/branches it shows that SerialTXBuffer is 6 commits ahead of master

I checked the files e.g 

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/SerialTXBuffer/STM32F1/system/libmaple/include/libmaple/usart.h#L385  and as you can see they appear to have the changes


Did you look in the SerialTXBuffer branch (Note. I could not pull locally to the branch name that @edogaldo  gave it, as Windows git would not accept the name)

**Comment by edogaldo** [comment]
It's strange that git didn't accept the name, I created it with the Windows git client under Windows 8.1

**Comment by rogerclarkmelbourne** [comment]
Perhaps I need to update my git client.

Actually after I had made by own branch name, I still couldnt pull from your repo, until I put quotes around your branch name.

But to save me a lot of hassle in my local git repo, I decided to stay with my own (simpler) name, as otherwise just switching to that branch, would be a hassle as I'd have to remember to put quotes around etc

**Comment by edogaldo** [comment]
No problem at all.

**Comment by RickKimball** [comment]
I was thrown by all the extra stuff in the branch you pointed at Roger. I was expecting just the pull request changes not the other modifications. I now see that this includes the pull request plus other goodness. Thanks.

**Comment by rogerclarkmelbourne** [comment]
OK.
Its just the latest master branch, into which I locally pulled the changes, so all I got was the changes

I guess your local master must have been a bit out of date, and as the F4 core etc is also in the same repo, it means the master changes when I update the F4 with bugs fixes I have been sent etc.

I think I should really move the F4 and F3 into different repo's as they only have the tools in common, and the F4 does not normally use the bootloader upload, so doesn't need those tools etc

**Pull request merged**
