### PR TITLE
Corrected: TIMER_CCMR1_CC2S_INPUT_TI*

### PR DESCRIPTION
**Pull request by lacklustrlabs**
According to STM32F103 RM0008: 
```
Bits 9:8 CC2S[1:0]: Capture/Compare 2 selection
This bit-field defines the direction of the channel (input/output) as well as the used input.
00: CC2 channel is configured as output
01: CC2 channel is configured as input, IC2 is mapped on TI2
10: CC2 channel is configured as input, IC2 is mapped on TI1
11: CC2 channel is configured as input, IC2 is mapped on TRC.
```

I had problems with this in #273

### CODE REVIEW

**Comment by stevstrong** [comment]
Overlapping with #323 which has already suggested a fix, but it was not yed merged.

**Comment by lacklustrlabs** [comment]
Nice catch, I'll change this so there won't be any merge conflicts with #323

**Comment by rogerclarkmelbourne** [comment]
@stevstrong 

I think I had some issues when I last tried https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/323 

I'll try pulling it locally and testing, but to fully test it, I'll need to setup to read back from the display and upload to the PC and I'll have to dig out the last code I had which kinda's does that, and modify it to make a usable test

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I've tested it with the a "tone" example and the tones play the same as before the change.

**Pull request merged**
