### PR TITLE
Adding Continuous Integration

### PR DESCRIPTION
**Pull request by ArminJo**
Here it is 😀 
First I prepared it for stm32duino:STM32F1:genericSTM32F103C, but it can easily be extended to other boards.
- I corrected a forgotten change in DhcpAddressPrinter
- The examples Debounce,StateChangeDetection,Button,QASlave,InteractiveTest,WhileStatementConditional were excluded, because of `QASlave.ino:61:21: error: 'BOARD_BUTTON_PIN' was not declared in this scope`.
- The examples HardwareTimerOnePulseMode,HardwareTimerPWMInput,StringEx_Parsing were excluded, because of `HardwareTimerPWMInput.ino:9:23: fatal error: Streaming.h: No such file or directory`.
- The OLED_I2C library has a bug for all examples.
and a lot more errors.
To see all errors, just comment the line sketches-exclude:
All results can be seen [here](https://github.com/ArminJo/Arduino_STM32/actions).

### CODE REVIEW

**Comment by ArminJo** [comment]
There are 2 directories or ino files which must be renamed, to be Arduino compatible.
- A_STM32_Examples/examples/Communication/MIDI to Midi
- RTClock/examples/RTCAdj/ to RTCAdjust

**Comment by stevstrong** [comment]
Is there anything which speaks against merging this PR?
If not, then I will merge it on Sunday at leteast.

**Comment by ArminJo** [comment]
I checked it again and it still runs without errors.
I added workflow_dispatch for manual build check. This is a very handy feature I use sometimes :-) .

**Comment by fpistm** [comment]
Great. Would recommend to simply do a `ln -s` instead of a copy of the repo. 😉

**Comment by ArminJo** [comment]
@fpistm Brilliant idea!

**Pull request merged**
