### PR TITLE
Add simple SPI slave example

### PR DESCRIPTION
**Pull request by VictorLamoine**
A very simple SPI slave example, I think the project lacks simple examples like this; it helps a lot getting things running!

### CODE REVIEW

**Comment by stevstrong** [comment]
Two comments:
- the SCLK, MISO and MOSI pin modes are already setup in the core.
- loop: wouldn't be more appropriate to use
`uint8_t msg = SPI.transfer(data);`
This replaces pushing the cnt value into DR and the read.

**Comment by victorpv** [comment]
Also as mentioned in the forum, setModule(1) is not needed since the SPI object uses SPI1 by default. 
Having setModule there may induce people to think it's needed in any case.

**Comment by VictorLamoine** [comment]
I have updated the code with your suggestions

**Comment by stevstrong** [comment]
After a more closer look into the core code, it seems that the NSS pin is also setup correctly by the core for slave mode, see: https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/1175f37c379513fbfc17bab75af4297d6f89e09f/STM32F1/cores/maple/libmaple/spi_f1.c#L71.
So the corresponding line in setup example can be also removed.

**Comment by VictorLamoine** [comment]
Ah cool, pull request updated!

**Comment by rogerclarkmelbourne** [comment]
Awaiting response to @stevstrong question about DMA enabling before things have been fully setup

**Comment by stevstrong** [comment]
I have to setup a master-slave configuration to test this, hope I can do it today.

**Comment by VictorLamoine** [comment]
> Awaiting response to @stevstrong question about DMA enabling before things have been fully setup
This example is without DMA?! I don't understand what you mean

I'll make an other pull request for the full duplex SPI with DMA slave.

**Comment by stevstrong** [comment]
Successfully tested the attached salve with the attached master.
I added to the slave a dummy SPI.read() to pre-empty the Rx pipe.

[STM32_SPI_master.ino.txt](https://github.com/rogerclarkmelbourne/Arduino_STM32/files/1958618/STM32_SPI_master.ino.txt)
[STM32_SPI_slave.ino.txt](https://github.com/rogerclarkmelbourne/Arduino_STM32/files/1958619/STM32_SPI_slave.ino.txt)

Would it make sense to add the master code to the slave as comment block?
I will also make a master and slave example for SPI with DMA.

**Comment by kvaale** [comment]
I get this error when trying to compile:
`'class SPIClass' has no member named 'beginTransactionSlave'; did you mean 'beginTransaction'?
`

along with:
`'DATA_SIZE_8BIT' was not declared in this scope; did you mean 'SPI_DATASIZE_8BIT'?`
...from the argument passed to the `SPI.beginTransactionSlave`-method.

I checked the commits on [SPI.h](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/libraries/SPI/src/SPI.h) but didn't find any changes regarding this `SPI.beginTransactionSlave`-method.
Am I missing something obvious? If so: sorry, I am noob.

**Pull request merged**
