### PR TITLE
Added the HID bootloader support

### PR DESCRIPTION
**Pull request by Serasidis**
Added a 4kb HID bootloader for bluepill board (STM32F103C8). Please
report any bug

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Hi Vassilis

I think its better if the bootloader source etc is in a separate repo.

I have a fork of the original repo.

So I will merge your changes into my fork and push them back to github

I think the "tools" and sources for tools are OK in this repo as we already have sources for other tools in the repo.

**Comment by rogerclarkmelbourne** [comment]
Vassilis

I've partially merged this.

What I've done is added your bootloader changes to my fork of the HID bootloader
https://github.com/rogerclarkmelbourne/stm32-hid-bootloader

In this repo, I've merged your change to use BKP register 10 as that will work with the DFU bootloader as well as the HID bootloader

I've also merged in the changes to platform.txt to support HID bootloader uploads and also added the uploader tool to the windows folder.

However I've not updated boards.txt or the generic_f103cx board variant, because I normally add the bootloader to all variants (where applicable)

I guess we only have a build for the bootloader for the BluePill etc but I need to do some more testing before I add it.

So I will leave this PR open

Thanks

**Comment by Serasidis** [comment]
Roger, I included the HID bootloader source code to the STM32duino because you already have the source code for other bootloaders in **Arduino_STM32/tools/win/src/** folder.
If you think that the  source code must not be included in that repo because the files are too many, you can do it. Besides, you know better than anyone else the structure of that repo.

I already made a fork from @bootsector github and I worked on that great repo. I talked to him and he wants to keep his HID bootloader repo in generic form. I respect that of course.
The problem is that I can not send him any pull request because of that reason.
I plan to make a new HID bootloader github repo customized for STM32 mcus. Do you agree with that ?

**Known bug:** When you burn the HID bootloader in a new bluepill the mcu jumps directly to the usercode. I am working on that to check during the mcu startup if there is a user code written in flash memory (address 0x08001000 - 0x08001003). If not, it will stay to the bootloader until a new firmware is written to the user code area.

**Comment by rogerclarkmelbourne** [comment]
Hi Vassilis

The source code for the bootloader is in a separate repo. But the source code for the download tools is in the tools folder(s)

So I agree that perhaps I could add the source for the uploader, but not for the bootloader

I assumed that @bootsector probably did not want this updates as he has a different use for this

I agree, its probably best to make your own repo for this.  I can then fork that repo if I need a copy

Or I could make a new repo (not a fork) and you could fork my copy ??

**Comment by rogerclarkmelbourne** [comment]
I'm closing this as its partially merged and the original PR is now out of date etc

**Pull request closed without merging**
