### PR TITLE
fix HardwareSerial::begin by doing gpio_set_af_mode AF8 when devices are UART4 or UART5

### PR DESCRIPTION
**Pull request by martinayotte**
Hi Roger,
Another small fix for a bug found in ad-hoc testing on my STM32F4Stamp.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Martin

Sorry to be pain, but I find its better if a Pull Request only fixes one issue at a time.

You seem to have change something in Hardware Serial, but you've also changed on of the ethernet libs at the same time. 

Are these changes linked in some way ?

**Comment by martinayotte** [comment]
Hi Roger,

 

Those are 2 separate commits in my branch, but I didnt create 2 separate
PR, thats maybe why GitHub shows you both at the same time.

But question of keeping history clean, Im not expert with git, I presume it
will stays as 2 separate commits in the master.

 

Regards,

 

  _____  

De : Roger Clark [mailto:notifications@github.com] 
Envoyé : Sunday, July 05, 2015 6:42 PM
À : rogerclarkmelbourne/Arduino_STM32
Cc : martinayotte
Objet : Re: [Arduino_STM32] fix HardwareSerial::begin by doing
gpio_set_af_mode AF8 when devices are UART4 or UART5 (#89)

 

Martin

Sorry to be pain, but I find its better if a Pull Request only fixes one
issue at a time.

You seem to have change something in Hardware Serial, but you've also
changed on of the ethernet libs at the same time. 

Are these changes linked in some way ?


Reply to this email directly or view
<https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/89#issuecomment-1
18672857>  it on GitHub.
<https://github.com/notifications/beacon/AJRhuGPB2AeC8BB2pD5YZjTKmQo11YrFks5
oaao9gaJpZM4FSNnR.gif>

**Comment by rogerclarkmelbourne** [comment]
Hi Martin,

OK. Actually now I look closer it says there are 3 commits.  So I'll action the PR and see how many commits end up in the master branch

**Comment by rogerclarkmelbourne** [comment]
Well, it seems to have done it as one commit to the master branch (unfortunately)

I'll bear this in mind in future, as its best to have separate commits in the master branch for separate bugs

But Neither of them were that major, so I don't think its worth reverting the pull etc and doing them manually one at at time.

**Comment by martinayotte** [comment]
Hi Roger,

 

Im not following you 

Yes, Ive done 3 commits, 2 for the separate bug fixes, and 1 for merge
back from your main branch using git merge upstream/master.

Maybe Im not an expert with Git, but it seems the way it should be done,
right ?

 

  _____  

De : Roger Clark [mailto:notifications@github.com] 
Envoyé : Monday, July 06, 2015 7:20 PM
À : rogerclarkmelbourne/Arduino_STM32
Cc : martinayotte
Objet : Re: [Arduino_STM32] fix HardwareSerial::begin by doing
gpio_set_af_mode AF8 when devices are UART4 or UART5 (#89)

 

Well, it seems to have done it as one commit to the master branch
(unfortunately)

I'll bear this in mind in future, as its best to have separate commits in
the master branch for separate bugs

But Neither of them were that major, so I don't think its worth reverting
the pull etc and doing them manually one at at time.


Reply to this email directly or view
<https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/89#issuecomment-1
19025495>  it on GitHub.
<https://github.com/notifications/beacon/AJRhuLGYP0A7Q0YMOoWEj0nlqhMzHY_0ks5
oawSWgaJpZM4FSNnR.gif>

**Comment by rogerclarkmelbourne** [comment]
Martin,

I'm not much of a Git expert either but it looks like your 3 commits are merged into one commit when they come via a PR. 

I think both of your commits are in this one commit into the master 

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/72171378756ff4328fc4b08351ee407434a9904b

I don't totally understand Pull requests myself.

Looking at the commit it says there are 2 parents, one is my previous commit to change names in boards.txt but the other parent looks like it only one of your two changes

Either way, I think if I was to Revent the pull request, I'd end up removing both changes.

So I suspect its better to do separate pull requests for separate fixes, as it makes it easier to revert if necessary 

(Note, Merging seems to cause me even more problems than PR's do. I find it very hard to revent a merge, so I tend to just commit PR's rather than making a new branch, applying the PR to the branch and then merging the new branch with the PR)

Also. Its probably not best practice, but I sometimes find it best just to make a copy of my whole local repo folder, and if something stuffs up in a local PR or merge, I just delete the whole local repo and go back to my copy prior to the merge or PR. 
It takes a bit longer to copy the folder, but is far eaiser than sometimes figuring out what the cryptic messages from Git are telling me, as some things are hard to recover from in Git and involve doing "hard resets" of the master branch - which seems a bit scary to me ;-)

**Comment by martinayotte** [comment]
Hi Roger,

 

Looking at your master branch history, it seems that PR still provide good
history since I see commits are actually separate :

 

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/09fbe056625f1d01
5ff434474187fca8b6c0cc48

https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/72171378756ff432
8fc4b08351ee407434a9904b

 

And it seems also that my other commits, the upstream/merge was understood
to be useless by Git since it was coming from your branch.

So, maybe Git is not so bad ;-), it is not always intuitive, even for
experimented users.

 

For PR mechanism, I suspect we need to live with it, since the order of
events was not under my control :

 

-          Bug fix #1 commit

-          Send the PR#1

-          Bug fix #2 commit

-          Wishing to send PR#2, I saw that PR#1 already include commit #2.
So, I didnt resend new PR, presuming it will be duplicates.

 

So, it seems to PR are only a flag sent between branches.

Then, it is up to the users to do cherry picking of commits themselves.
Let says in current case that you wouldnt agree about fix#1, you can still
take the fix#2.

How to do this cherry picking ? This is maybe where we both need to learn,
even more important for you than me :-) 

(I will googled it tomorrow)

 

Let try it out next time,

 

Ciao.

 

  _____  

De : Roger Clark [mailto:notifications@github.com] 
Envoyé : Monday, July 06, 2015 8:37 PM
À : rogerclarkmelbourne/Arduino_STM32
Cc : martinayotte
Objet : Re: [Arduino_STM32] fix HardwareSerial::begin by doing
gpio_set_af_mode AF8 when devices are UART4 or UART5 (#89)

 

Martin,

I'm not much of a Git expert either but it looks like your 3 commits are
merged into one commit when they come via a PR. 

I think both of your commits are in this one commit into the master 

 
<https://github.com/rogerclarkmelbourne/Arduino_STM32/commit/72171378756ff43
28fc4b08351ee407434a9904b> 7217137

I don't totally understand Pull requests myself.

Looking at the commit it says there are 2 parents, one is my previous commit
to change names in boards.txt but the other parent looks like it only one of
your two changes

Either way, I think if I was to Revent the pull request, I'd end up removing
both changes.

So I suspect its better to do separate pull requests for separate fixes, as
it makes it easier to revert if necessary 

(Note, Merging seems to cause me even more problems than PR's do. I find it
very hard to revent a merge, so I tend to just commit PR's rather than
making a new branch, applying the PR to the branch and then merging the new
branch with the PR)

Also. Its probably not best practice, but I sometimes find it best just to
make a copy of my whole local repo folder, and if something stuffs up in a
local PR or merge, I just delete the whole local repo and go back to my copy
prior to the merge or PR. 
It takes a bit longer to copy the folder, but is far eaiser than sometimes
figuring out what the cryptic messages from Git are telling me, as some
things are hard to recover from in Git and involve doing "hard resets" of
the master branch - which seems a bit scary to me ;-)


Reply to this email directly or view
<https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/89#issuecomment-1
19035336>  it on GitHub.
<https://github.com/notifications/beacon/AJRhuF-f2mFXiOppBmOOgYahpOxwlJ64ks5
oaxaugaJpZM4FSNnR.gif>

**Pull request merged**
