### PR TITLE
Increment size of emulated EEPROM

### PR DESCRIPTION
**Pull request by svmac**
Defines paremeter Pages for use more than one page per bank on emulated EEPROM.

### CODE REVIEW

**Comment by stevstrong** [comment]
Do you have a simple test sketch to demonstrate the functionality and the advantages it brings?

**Comment by svmac** [comment]
Yes, I have already modified the example, look at it. Option 1 uses two pages.

**Comment by stevstrong** [comment]
How far is this compatible with the previous version and what problem is solved with this?

**Comment by svmac** [comment]
It is 100% compatible, because Pages are set to 1 by default, so if you do not use (reference) Pages then it is like the previous version.
Solve when you need more EEPROM storage.

**Comment by stevstrong** [comment]
Looks good, so I will merge this.

**Pull request merged**
