### PR TITLE
upgrade to latest USBComposite library

### PR DESCRIPTION
**Pull request by arpruss**
Many major and minor updates to the library.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Wow. That's amazing

@stevstrong 
Do you have time to do any testing of this.

I may be able to test it this weekend.

**Comment by arpruss** [comment]
For testing, I recommend trying some random things from its examples directory, though I've been using this library pretty continuously.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks

**Comment by rogerclarkmelbourne** [comment]
None of the examples will compile 

I seem to get the same error on all examples

```
hardware\Arduino_STM32\STM32F1\libraries\USBComposite\usb_x360.c:275:9: error: unknown field  bufferSize  specified in initializer

         .bufferSize = 0x20,

D:\Documents\Arduino\hardware\Arduino_STM32\STM32F1\libraries\USBComposite\usb_x360.c:281:9: error: unknown field 'bufferSize' specified in initializer

         .bufferSize = 0x20,
```



And loads of warnings.

Did you commit and push all of the files ?

**Comment by arpruss** [comment]
The problem was the opposite: I failed to delete two old files.

**Comment by rogerclarkmelbourne** [comment]
OK.

I'll pull again and retest

**Comment by rogerclarkmelbourne** [comment]
Sorry its taken ages to look at this

I am still getting an error

\STM32F1\libraries\USBComposite\USBXBox360.cpp:27:22: fatal error: usb_x360.h: No such file or directory

 #include "usb_x360.h"

When compiling any of the examples

**Comment by rogerclarkmelbourne** [comment]
BTW. I did a clean pull from your repo.

**Comment by arpruss** [comment]
I don't understand this, since there is no #include for usb_x360.h anywhere in the library.

**Comment by rogerclarkmelbourne** [comment]
https://github.com/arpruss/Arduino_STM32/blob/master/STM32F1/libraries/USBComposite/USBXBox360.cpp

**Comment by arpruss** [comment]
Oops: that's another leftover file from the previous version. Deleted.

**Comment by rogerclarkmelbourne** [comment]
Thanks. Its compiling OK now, but I'll need to test one or two of the examples, before I can merge the PR

**Comment by rogerclarkmelbourne** [comment]
Works amazingly well.

Thankyou

**Pull request merged**
