### PR TITLE
Fix for sprintf when compiling with nano.specs option set.

### PR DESCRIPTION
**Pull request by danieltr3s**
Fix suggested by @HamidSaffari in issue https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/620 .

### CODE REVIEW

**Comment by kad** [comment]
+1 for this fix

**Comment by stevstrong** [comment]
Was this tested by anyone?

**Comment by kad** [comment]
> Was this tested by anyone?

I tried it with small hack in Marlin 2.0.7.2 firmware. builds fine, in places where it was broken, now seems to print floats ok.

https://github.com/kad/Marlin/commit/90878465bbc458ed516d325e9fa7629a056f3039#diff-f8926a81e11f2d9a94bb619e586b96c7d3cd4452a5e63d1b2c215efd0071a346

**Comment by stevstrong** [comment]
Is there a simple skecth wich shows the problem and the solution?

**Comment by fpistm** [comment]
If it can help, it is used since a while in STM32 core.
Note that is is also used by String class:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/59227d1ecab7e931a390119c20655f1c4147a668/STM32F1/cores/maple/WString.cpp#L114

You can use this sketch to test:

```c++
void setup() {
  bool validate = true;
  char sout[256] = "";

  Serial.begin(9600);
  while (!Serial);

  Serial.println(dtostrf(1.23, 7, 2, sout));
  if (strcmp(sout, "   1.23") != 0) {
    validate = false;
  }
  Serial.println(dtostrf(1.899, 2, 2, sout));
  if (strcmp(sout, "1.90") != 0) {
    validate = false;
  }
  Serial.println(dtostrf(-123456.78910, 127, 6, sout));
  if (strcmp(sout,
             "                                                                                                                 -123456.789100"
            ) != 0) {
    validate = false;
  }
  Serial.println(dtostrf(-123456.78910, 128, 6, sout));
  if (strcmp(sout,
             "-123456.789100                                                                                                                  "
            ) != 0) {
    validate = false;
  }

  if (validate) {
    Serial.println("SUCCESS");
  } else {
    Serial.println("FAILED");
  }

}

void loop() {
}
```

**Comment by stevstrong** [comment]
I have tested it and it seems to work, so I will merge this.

**Comment by stevstrong** [comment]
this also solves #620.

**Pull request merged**
