### PR TITLE
Black f4 variant

### PR DESCRIPTION
**Pull request by stevstrong**
- added variant for black F407VET6 board
- cleanup of F1 and F2 definitions

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
@stevstrong 

Looking at the "Files changed", it looks like this change is not limited to the F4 but also changes a lot of files in the F1 e.g. in the SPI.

This may be just the way that github is displaying things,
I'd love to accept the PR for the F4 only, but I can't accept it if it also changes F1 in the same PR

@victorpv  does it look the same to you

**Comment by stevstrong** [comment]
Hi Roger,
nice to here from you again :)
Although I made a separate branch for F4 changes, somehow the old F1 - SPI related stuff was also included into this PR, I don't know why and how... It maybe because those changes were not yet committed to the main branch?
Sorry for this, I still cannot understand how Github works, it stays a "mystery" for me...
I don't know what to do to have only those changes in a PR.
The only black F4 branch related changes are after Victor's comment on 22 Feb.

**Comment by rogerclarkmelbourne** [comment]
Hi @stevstrong 

No worries..

I've been away (unexpectedly)  for the last month, but I am back now, and slowly looking at the backlog of issues

**Comment by victorpv** [comment]
I also see the F1 files modified. 
Steve, as far as I can see, when you submit a PR in github from a branch to another, if you keep adding commits to the source of the commit, all those modifications will be part of the PR, even if those commits are submitted at a much later date than the PR.
The only way around it I found when looking for a solution is to create a new branch off your code with what you want to include in a PR, then you don't modify that branch again until the PR is approved and merged.

**Comment by victorpv** [comment]
Example, this one I did to add a function for the timers DMS:
https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/262/files
If you look at it, I created a separate branch called timer_dma, and I haven't touched that branch again. I created that branch only for submitting the PR. When Roger approves it I will just delete that branch and merge again from his master.

**Comment by stevstrong** [comment]
Yes, I did the same with Black_F4 branch. Created, then made F4-relevant changes. 
With Girhub for Windows (locally) I see onyl these changes for this branch.
Still, Github added hereto the old F1 SPI-related changes, too. Don't know why.

**Comment by stevstrong** [comment]
Yes, I did the same with Black_F4 branch. Created, then made F4-relevant changes.
With Girhub for Windows (locally) I see only these changes for this branch.
Still, Github added hereto the old F1 SPI-related changes, too. Don't know why.

**Comment by rogerclarkmelbourne** [comment]
@stevstrong , I think you may need to do a new PR for the " Black_F4_variant " branch

Also, you probably need to check if any of the F1 files were changed in the point in the git history from which you branched.
i.e you may need to switch to an old commit that doesnt have the F1 changes, and then branch from that older commit.

**Comment by stevstrong** [comment]
OK, I will try your last suggestion.

**Comment by rogerclarkmelbourne** [comment]
OK.

Thanks.

**Comment by rogerclarkmelbourne** [comment]
Sorry, The latest changes still include F1 code  for SPI

Probably the best thing I can do is to check this out to a new local branch, then copy out the new F4 files, then switch to the master branch and copy the F4 files into my master branch

This would still leave this PR containing the F1 changes, but we could then close this PR

**Comment by rogerclarkmelbourne** [comment]
Has this been superseded ?

It now has merge conflicts in the F4 folder and also it seems to also change the F1, when its only for the F4 :-(

**Comment by stevstrong** [comment]
I'll check this later today.

**Comment by rogerclarkmelbourne** [comment]
No rush

**Pull request closed without merging**
